#!/bin/bash
# RTSP 推流测试脚本

echo "=== RTSP 推流测试 ==="
echo ""
echo "1. 确保程序已编译"
echo "   cd /home/linaro/EASY-EAI-Toolkit-1126B/src"
echo "   ./build_camera_streaming.sh"
echo ""
echo "2. 启动 RTSP 推流（在板子上运行）"
echo "   cd ../build"
echo "   ./camera_streaming --rtsp --width 1920 --height 1080 --fps 30"
echo ""
echo "3. 在另一个终端或PC上测试连接"
echo ""
echo "测试方法 1: 使用 ffplay"
echo "   ffplay -rtsp_transport tcp rtsp://192.168.1.83:8554/stream"
echo ""
echo "测试方法 2: 使用 VLC"
echo "   vlc --network-caching=300 rtsp://192.168.1.83:8554/stream"
echo ""
echo "测试方法 3: 使用 GStreamer"
echo "   gst-launch-1.0 rtspsrc location=rtsp://192.168.1.83:8554/stream ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! autovideosink"
echo ""
echo "测试方法 4: 使用 ffprobe 查看流信息"
echo "   ffprobe -rtsp_transport tcp rtsp://192.168.1.83:8554/stream"
echo ""
echo "调试选项:"
echo "   - 如果连接失败，尝试添加 -rtsp_transport tcp"
echo "   - 如果延迟高，尝试添加 -fflags nobuffer -flags low_delay"
echo "   - 查看服务器日志了解客户端连接状态"
echo ""
echo "常见问题:"
echo "   1. 连接超时 → 检查防火墙，确保 8554 端口开放"
echo "   2. 无法加载 → 检查服务器日志，确认 'Client connected!' 消息"
echo "   3. 卡顿 → 降低分辨率或帧率"
echo ""
