#pragma once

#define ARRAY_SIZE(x) (sizeof(x) / sizeof((x)[0]))
#define CAMERA_WIDTH    2688
#define CAMERA_HEIGHT   1520
#define IMAGE_WIDTH     1280
#define IMAGE_HEIGHT    720
#define CAMERA_INDEX_1  11
#define CAMERA_INDEX_2  51
#define DEFAULT_CAMERA_NUMBER 1
#define CAMERA_FORMAT   RK_FORMAT_BGR_888  
#define IMGRATIO        3
#define IMAGE_SIZE      (CAMERA_WIDTH*CAMERA_HEIGHT*IMGRATIO)
#define MAX_MISSED      45

#define PERSON_MODEL_PATH   "person_detect.model"
#define FACE_MODEL_PATH     "face_detect.model"

#define RETIAN_MODEL_TYPE   0 
#define RETIAN_INPUT_H      480
#define RETIAN_INPUT_W      640
#define RETIAN_CONF_THRESH  0.7f
#define RETIAN_NMS_THRESH   0.4f

// 抓拍与性能调优参数
#define CAPTURE_MIN_CLARITY              80.0
#define CAPTURE_MAX_MOTION_RATIO         0.020f
#define CAPTURE_MAX_MOTION_REJECT_RATIO  0.050f
#define CAPTURE_PERSON_DETECT_INTERVAL   2
#define CAPTURE_FACE_DETECT_INTERVAL    2
#define CAPTURE_FACE_INPUT_MAX_WIDTH    512
#define CAPTURE_MAX_FRAME_CANDIDATES    48
#define CAPTURE_CANDIDATE_QUEUE_MAX     128
#define CAPTURE_CANDIDATE_PER_TRACK_MAX_PENDING 6
#define CAPTURE_PERSON_CONTEXT_EXPAND_X 0.12f
#define CAPTURE_PERSON_CONTEXT_EXPAND_TOP 0.18f
#define CAPTURE_PERSON_CONTEXT_EXPAND_BOTTOM 0.10f
#define CAPTURE_MIN_FACE_SCORE          0.55f
#define CAPTURE_HEADSHOT_EXPAND_RATIO   1.80f
#define CAPTURE_HEADSHOT_DOWN_SHIFT     0.20f
#define CAPTURE_FOCUS_SCALE_FACTOR      3
#define CAPTURE_MIN_AREA_RATIO          0.025f
#define CAPTURE_NEAR_AREA_RATIO         0.065f
#define CAPTURE_APPROACH_RATIO_POS      0.08f
#define CAPTURE_APPROACH_RATIO_NEG     -0.08f
#define CAPTURE_MIN_TRACK_HITS          2
#define CAPTURE_REQUIRE_APPROACH        1
#define CAPTURE_REQUIRE_FRONTAL_FACE    1
#define CAPTURE_MAX_YAW                 0.8f
#define CAPTURE_STRONG_FRONTAL_MAX_ROLL 15.0f
#define CAPTURE_STRONG_FRONTAL_MAX_YAW  0.18f
#define CAPTURE_FACE_MIN_AREA_IN_PERSON 0.030f
#define CAPTURE_FACE_MIN_WIDTH_RATIO    0.12f
#define CAPTURE_FACE_MIN_CENTER_Y_RATIO 0.10f
#define CAPTURE_FACE_MAX_CENTER_Y_RATIO 0.52f
#define CAPTURE_MIN_FACE_BOX_SHORT_SIDE 96
#define CAPTURE_MIN_FACE_BOX_AREA       14000
#define CAPTURE_MAX_PERSON_OCCLUSION    0.45f
#define CAPTURE_MAX_FACE_EDGE_OCCLUSION 0.55f
#define CAPTURE_FACE_EDGE_MIN_MARGIN    0.08f
#define CAPTURE_HEADSHOT_MIN_FACE_MARGIN 0.12f
#define CAPTURE_MOTION_SCORE_PENALTY    220.0f
#define CAPTURE_OCCLUSION_SCORE_PENALTY 260.0f

// 亮度与IR-CUT配置
#define CAMERA_BRIGHTNESS_SAMPLE_INTERVAL  5
#define CAMERA_BRIGHTNESS_WHITE_THRESHOLD  110.0
#define CAMERA_BRIGHTNESS_BLACK_THRESHOLD   85.0